"""Extreme-value and point-process tests (B12 beacon, B13 budget, B24 tails).

STATUS: implemented. Signatures are frozen (docs/lib3/helpers_api.md); where
the maths departs from the original stub (null-table grids, window-corrected
Z^2, Davies trials bound) it is marked DEVIATION below, with the measurement
that forced it, and listed in helpers_api.md.

Why PWM for the GPD: with 10-30 exceedances maximum likelihood is unstable
and slow; probability-weighted moments (Hosking & Wallis 1987) are closed
form, O(n log n), and well behaved for xi in [-0.5, 0.5], which is the range
we clip to anyway.

Why a Gamma renewal LRT for beacons: a C2 implant with +-30% jitter is a
renewal process whose intervals are Gamma-like with shape kappa >> 1, while
human / Poisson traffic has kappa <= 1. Phase-based tests (Rayleigh,
Lomb-Scargle) lose coherence under renewal jitter (measured Rayleigh median
p = 0.14 at n = 40). The chi2_1 asymptotic of the LRT is 2-5x
anti-conservative at n <= 40, hence the tabulated finite-n null.

Why the null table is *exact* rather than Monte-Carlo: the LR depends on
the intervals only through s = ln(mean x) - mean(ln x) and is monotone in s,
so P0(LR >= c) = P0(s <= s_c). Under i.i.d. Exp intervals x / sum(x) is
Dirichlet(1, ..., 1), which gives the Mellin transform of T = n s in closed
form: E[exp(u T)] = n^(-n u) Gamma(n) Gamma(1 - u)^n / Gamma(n (1 - u)).
Inverting it on a Bromwich line through the saddlepoint (trapezoid rule,
spectrally accurate) gives P0(T <= t) to ~1e-12 in log p at any depth,
where 1e5 simulations resolve nothing below ~1e-4. scripts/gen_beacon_null.py
builds the constants that way and checks them against >= 2e4 Monte-Carlo
draws per n (bulk) and Dirichlet-tilted importance sampling (tail).

Why the Z^2 scan is window-corrected and uses an upcrossing bound: measured
on Poisson event times, the stub's Bonferroni n_eff * chi2.sf was 2-5x
anti-conservative at alpha <= 1e-2 (an oversampled scan of a chi2 process
has ~sqrt(z/2) more effective trials than independent Fourier frequencies,
Davies 1987), and 12x at n = 256 because a non-integer number of cycles
over the observation window biases Z^2 upwards at the lowest frequencies.
Subtracting the window's expected phasor and using the Davies bound gives
realised / nominal 0.2-0.9 for n = 12..256 at 1e-1..1e-3. The first and
last events define the window, so they sit at phases 0 and 2 pi T/P by
construction and only the n - 2 interior times are uniform: the expected
phasor is 1 + e^(i theta) + (n - 2) w, not n w (the latter left a mean of up
to 2 per harmonic, which made the union bound 1.25-1.7x anti-conservative
at n = 20..40). With that, min(Davies, L chi2.sf) realises 0.15-1.0x
nominal at 1e-1..1e-3 for n = 12..256 (2e4 Poisson streams per case).
"""
from __future__ import annotations

import math
from bisect import bisect_left, bisect_right
from typing import List, Optional, Sequence, Tuple

import numpy as np
from scipy import special

XI_CLIP = (-0.5, 0.5)
MIN_INTERVAL_S = 1e-3            # intervals are clipped below at 1 ms before logs
KAPPA_MAX = 1e6                  # kappa_hat cap (s ~ 0: all intervals equal)
Z2_MAX_TRIALS = 512              # trial-period cap of z2_trial_periods
Z2_MIN_OVERSAMPLE = 2.0          # a capped grid coarsens down to this first
P_FLOOR = 1e-300                 # smallest p returned (same as combine.P_FLOOR)

_XI_ZERO = 1e-9                  # |xi| below this is the exponential limit
_TINY = 1e-12                    # sigma floor of the exponential fallback
_NEWTON_STEPS = 4
_NEWTON_TOL = 1e-8
_LN10 = math.log(10.0)
_HALF_LN_2PI = 0.5 * math.log(2.0 * math.pi)
_K_ASYM = 20.0                   # kappa >= this: asymptotic series (_shape_terms)
_MC_MIN_TAIL = 10.0              # MC quantile needs >= 10 expected exceedances
_Z2_UNIFORM_RTOL = 1e-12         # frequency grid counts as uniform below this
_Z2_CHUNK = 1 << 16              # direct Z^2 path: max trials x events per block

# ---- Null of the Gamma renewal LR (B12) -------------------------------------
# Layout:
#   BEACON_NULL_N      : sorted int grid of interval counts n (8 .. 256;
#                        n = events - 1, so B12's '12 events' is row 11)
#   BEACON_NULL_LOG10P : descending grid of log10 upper-tail probabilities
#   BEACON_NULL_LR     : float array [len(N), len(LOG10P)], the LR quantile
#                        with P_null(LR >= value) = 10**log10p (one-sided,
#                        LR = 0 when kappa_hat <= 1: P(LR = 0) = 0.35 at
#                        n = 8 .. 0.47 at n = 256).
# Values: exact null (module docstring), generated by
# scripts/gen_beacon_null.py and validated there against Monte-Carlo and
# importance sampling. DEVIATIONS from the stub: the n grid starts at 8
# (not 12) so a 12-event stream (11 intervals) gets a p, and the p grid reaches
# 1e-12 (not 1e-5) so that alarm-level p-values (~1e-6 .. 1e-9 for real beacons) are
# interpolated, not extrapolated with the chi2 shape, which is itself
# anti-conservative there. Rows decrease in n at every p, so using the row
# of the largest tabulated n' <= n is conservative.
BEACON_NULL_N: Tuple[int, ...] = (8, 9, 10, 11, 12, 14, 16, 20, 24, 32, 40, 48, 64, 96, 128,
                                  192, 256)
BEACON_NULL_LOG10P: Tuple[float, ...] = (
    -0.30103, -0.5, -1.0, -1.5, -2.0, -2.5, -3.0, -3.5, -4.0, -4.5, -5.0, -5.5, -6.0,
    -6.5, -7.0, -7.5, -8.0, -8.5, -9.0, -9.5, -10.0, -10.5, -11.0, -11.5, -12.0)
# generated by: .venv/bin/python scripts/gen_beacon_null.py (exact; MC/IS-checked)
BEACON_NULL_LR: np.ndarray = np.array([
    [0.169072, 0.823128, 3.036974, 5.490526, 8.025436, 10.598490, 13.192433,
     15.798899, 18.413313, 21.032969, 23.656170, 26.281813, 28.909161, 31.537707,
     34.167104, 36.797104, 39.427536, 42.058276, 44.689238, 47.320358, 49.951592,
     52.582908, 55.214283, 57.845700, 60.477148],  # n=8
    [0.147500, 0.770711, 2.921421, 5.320082, 7.803945, 10.328257, 12.875039,
     15.435517, 18.004859, 20.580178, 23.159643, 25.742044, 28.326557, 30.912603,
     33.499773, 36.087771, 38.676382, 41.265448, 43.854853, 46.444510, 49.034356,
     51.624344, 54.214437, 56.804609, 59.394840],  # n=9
    [0.130806, 0.728930, 2.828766, 5.183537, 7.626761, 10.112377, 12.621785,
     15.145864, 17.679568, 20.219862, 22.764808, 25.313113, 27.863884, 30.416488,
     32.970468, 35.525488, 38.081298, 40.637712, 43.194588, 45.751819, 48.309323,
     50.867037, 53.424913, 55.982914, 58.541012],  # n=10
    [0.117503, 0.694719, 2.752501, 5.071238, 7.481231, 9.935288, 12.414269,
     14.908753, 17.413508, 19.925373, 22.442320, 24.962989, 27.486433, 30.011973,
     32.539115, 35.067491, 37.596824, 40.126903, 42.657565, 45.188685, 47.720165,
     50.251929, 52.783917, 55.316083, 57.848389],  # n=11
    [0.106655, 0.666104, 2.688411, 4.976937, 7.359174, 9.786935, 12.240608,
     14.710507, 17.191234, 19.679521, 22.173262, 24.671039, 27.171859, 29.675006,
     32.179957, 34.686317, 37.193785, 39.702132, 42.211177, 44.720779, 47.230828,
     49.741236, 52.251933, 54.762861, 57.273978],  # n=12
    [0.090029, 0.620735, 2.586175, 4.826658, 7.164967, 9.551253, 11.965105,
     14.396387, 16.839425, 19.290766, 21.748174, 24.210136, 26.675583, 29.143745,
     31.614047, 34.086055, 36.559433, 39.033922, 41.509314, 43.985446, 46.462185,
     48.939425, 51.417077, 53.895073, 56.373352],  # n=14
    [0.077886, 0.586169, 2.507713, 4.711458, 7.016374, 9.371262, 11.755058,
     14.157261, 16.571970, 18.995578, 21.425745, 23.860878, 26.299851, 28.741846,
     31.186252, 33.632603, 36.080540, 38.529778, 40.980091, 43.431299, 45.883254,
     48.335835, 50.788942, 53.242493, 55.696420],  # n=16
    [0.061337, 0.536479, 2.393935, 4.544636, 6.801675, 9.111773, 11.452862,
     13.813871, 16.188541, 18.573031, 20.964831, 23.362227, 25.764002, 28.169266,
     30.577351, 32.987746, 35.400052, 37.813953, 40.229196, 42.645575, 45.062921,
     47.481094, 49.899978, 52.319475, 54.739503],  # n=20
    [0.050588, 0.502058, 2.314335, 4.428099, 6.652065, 8.931403, 11.243293,
     13.576240, 15.923717, 18.281702, 20.647561, 23.019485, 25.396188, 27.776725,
     30.160385, 32.546623, 34.935012, 37.325211, 39.716948, 42.109999, 44.504181,
     46.899340, 49.295350, 51.692102, 54.089503],  # n=24
    [0.037458, 0.456690, 2.208272, 4.273053, 6.453539, 8.692698, 10.966646,
     13.263279, 15.575689, 17.899597, 20.232185, 22.571512, 24.916189, 27.265194,
     29.617752, 31.973268, 34.331272, 36.691391, 39.053322, 41.416818, 43.781675,
     46.147721, 48.514812, 50.882826, 53.251658],  # n=32
    [0.029739, 0.427555, 2.139361, 4.172465, 6.325087, 8.538677, 10.788612,
     13.062367, 15.352771, 17.655365, 19.967206, 22.286257, 24.611061, 26.940536,
     29.273866, 31.610419, 33.949697, 36.291300, 38.634907, 40.980252, 43.327116,
     45.675315, 48.024693, 50.375118, 52.726478],  # n=40
    [0.024657, 0.406935, 2.090157, 4.100713, 6.233637, 8.429242, 10.662358,
     12.920147, 15.195239, 17.483043, 19.780519, 22.085563, 24.396661, 26.712692,
     29.032805, 31.356341, 33.682780, 36.011704, 38.342776, 40.675716, 43.010295,
     45.346317, 47.683620, 50.022063, 52.361527],  # n=48
    [0.018377, 0.379189, 2.023310, 4.003332, 6.109764, 8.281319, 10.492045,
     12.728661, 14.983516, 17.251829, 19.530425, 21.817101, 24.110265, 26.408737,
     28.711620, 31.018214, 33.327968, 35.640438, 37.955263, 40.272145, 42.590837,
     44.911131, 47.232850, 49.555843, 51.879982],  # n=64
    [0.012175, 0.347986, 1.947140, 3.892497, 5.969136, 8.113842, 10.299727,
     12.512976, 14.745601, 16.992591, 19.250610, 21.517332, 23.791075, 26.070587,
     28.354910, 30.643300, 32.935166, 35.230032, 37.527508, 39.827275, 42.129064,
     44.432649, 46.737839, 49.044470, 51.352399],  # n=96
    [0.009103, 0.330218, 1.903230, 3.828663, 5.888321, 8.017827, 10.189728,
     12.389888, 14.610115, 16.845260, 19.091888, 21.347601, 23.610661, 25.879770,
     28.153938, 30.432391, 32.714514, 34.999812, 37.287879, 39.578380, 41.871034,
     44.165605, 46.461892, 48.759722, 51.058947],  # n=128
    [0.006050, 0.309908, 1.852496, 3.754960, 5.795177, 7.907378, 10.063437,
     12.248831, 14.455123, 16.677001, 18.910911, 21.154366, 23.405561, 25.663149,
     27.926094, 30.193589, 32.464992, 34.739781, 37.017533, 39.297893, 41.580567,
     43.865306, 46.151897, 48.440157, 50.729928],  # n=192
    [0.004530, 0.298181, 1.822915, 3.712011, 5.740980, 7.843221, 9.990201,
     12.167164, 14.365528, 16.579880, 18.806596, 21.043137, 23.287657, 25.538776,
     27.795434, 30.056804, 32.322225, 34.591163, 36.863179, 39.137912, 41.415057,
     43.694356, 45.975590, 48.258571, 50.543136],  # n=256
])
BEACON_NULL_LR.setflags(write=False)


# ============================================================ GPD / POT
def gpd_pwm_fit(exceedances: Sequence[float]) -> Tuple[float, float]:
    """(xi, sigma) of a GPD fitted to excesses y = x - u >= 0 by PWM.

    y sorted ascending, n = len(y), plotting positions p_i = (i - 0.35)/n,
        a0 = mean(y),  a1 = mean((1 - p_i) y_i)
        xi    = 2 - a0 / (a0 - 2 a1)
        sigma = 2 a0 a1 / (a0 - 2 a1)
    (xi > 0 = heavy tail). xi is clipped to XI_CLIP; if clipped, sigma is
    re-estimated from the mean, sigma = a0 (1 - xi). n < 3, a0 <= 0 or
    a0 - 2 a1 <= 0 -> (0.0, max(a0, tiny)) (exponential fallback; with y
    ascending and a0 > 0, a0 - 2 a1 = mean(y (2 p_i - 1)) > 0 by Chebyshev's
    sum inequality, so this only guards rounding). NaNs (and +-inf) are
    dropped first. O(n log n).
    """
    y = np.asarray(exceedances, dtype=np.float64).ravel()
    y = np.sort(y[np.isfinite(y)])
    n = y.size
    a0 = float(y.mean()) if n else 0.0
    if n < 3 or not a0 > 0.0:
        return 0.0, max(a0, _TINY)
    p = (np.arange(1, n + 1) - 0.35) / n
    a1 = float(np.mean((1.0 - p) * y))
    d = a0 - 2.0 * a1
    if not d > 0.0:
        return 0.0, max(a0, _TINY)
    xi = 2.0 - a0 / d
    sigma = 2.0 * a0 * a1 / d
    lo, hi = XI_CLIP
    if not lo <= xi <= hi:
        xi = min(hi, max(lo, xi))
        sigma = a0 * (1.0 - xi)
    return float(xi), float(sigma)


def gpd_sf(y: np.ndarray, xi: float, sigma: float) -> np.ndarray:
    """P(Y > y) = (1 + xi y / sigma)^(-1/xi); |xi| < 1e-9 -> exp(-y / sigma).

    For xi < 0 the support ends at -sigma/xi: sf = 0 beyond it (callers floor
    at 1e-300). y <= 0 -> 1. Computed in log space (log1p). NaN -> NaN.
    Returns an array of y's shape. Invalid parameters (non-finite xi,
    sigma <= 0 or non-finite) give NaN wherever y > 0.
    """
    y = np.asarray(y, dtype=np.float64)
    xi = float(xi)
    sigma = float(sigma)
    with np.errstate(invalid="ignore", divide="ignore", over="ignore"):
        if not (math.isfinite(xi) and sigma > 0.0 and math.isfinite(sigma)):
            out = np.where(y > 0.0, np.nan, 1.0)
        else:
            z = np.maximum(y, 0.0) / sigma
            if abs(xi) < _XI_ZERO:
                out = np.exp(-z)
            else:
                t = xi * z
                inside = t > -1.0                  # False only beyond the xi < 0 end point
                out = np.where(inside, np.exp(-np.log1p(np.where(inside, t, 0.0)) / xi), 0.0)
            out = np.where(y > 0.0, out, 1.0)
    return np.where(np.isnan(y), np.nan, out)


def pot_sf(x: np.ndarray, u: float, xi: float, sigma: float, rate: float) -> np.ndarray:
    """Peaks-over-threshold tail: P(X > x) = rate * gpd_sf(x - u) for x > u (rate = N_u/N).

    x <= u lies in the empirical body, about which the tail model says
    nothing: it returns 1.0 (no evidence; a caller wanting the body uses
    its empirical p). rate is clipped to [0, 1]. NaN x -> NaN; a NaN u or
    rate -> all NaN.
    """
    x = np.asarray(x, dtype=np.float64)
    u = float(u)
    rate = float(rate)
    if not (math.isfinite(u) and rate == rate):
        return np.full(x.shape, np.nan)
    rate = min(1.0, max(0.0, rate))
    with np.errstate(invalid="ignore"):
        out = np.where(x > u, rate * gpd_sf(x - u, xi, sigma), 1.0)
    return np.where(np.isnan(x), np.nan, out)


def pot_quantile(u: float, xi: float, sigma: float, rate: float, q: float) -> float:
    """Level z_q with P(X > z_q) = q under the POT model (B13 budget threshold):

        z_q = u + sigma / xi * ((rate / q)^xi - 1)   (xi != 0)
        z_q = u + sigma * ln(rate / q)               (|xi| < 1e-9)
    q >= rate returns u (the level is inside the empirical body). Computed
    as sigma/xi * expm1(xi ln(rate/q)), so q -> 0 gives +inf for xi >= 0 and
    the end point u - sigma/xi for xi < 0 (overflow -> +inf, not an
    exception). rate is clipped to [0, 1] as in pot_sf, so the two stay
    inverse. Any NaN input, or sigma <= 0 / non-finite -> NaN (as gpd_sf).
    """
    u, xi, sigma, rate, q = float(u), float(xi), float(sigma), float(rate), float(q)
    if any(v != v for v in (u, xi, sigma, rate, q)) or not 0.0 < sigma < math.inf:
        return math.nan
    rate = min(1.0, max(0.0, rate))
    if q >= rate:
        return u
    log_ratio = math.inf if q <= 0.0 else math.log(rate) - math.log(q)
    if abs(xi) < _XI_ZERO:
        return u + sigma * log_ratio
    a = xi * log_ratio
    return u + (math.inf if a > 700.0 else sigma / xi * math.expm1(a))


# ======================================================== Gamma renewal LRT
def _log_ratio_stat(x: np.ndarray) -> np.ndarray:
    """s = ln(mean x) - mean(ln x) along the last axis, as mean(d - log1p(d))
    with d = x/mean - 1: every term is >= 0 and there is no cancellation
    between two O(ln x) numbers, so s ~ 1e-9 (near-constant intervals) is
    accurate."""
    m = x.mean(axis=-1, keepdims=True)
    d = x / m - 1.0
    return np.mean(d - np.log1p(d), axis=-1)


def _shape_terms(k: np.ndarray) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """(ln k - digamma(k), 1/k - trigamma(k), k ln k - lnGamma(k) - k), vectorised.

    Each is a difference of O(ln k) or O(k ln k) numbers that cancel to
    O(1/k) or O(ln k): at k = 5e5 lnGamma alone is 6e6, so two libm's
    roundings disagree in the 9th digit of LR. For k >= _K_ASYM the
    asymptotic (Stirling / de Moivre) series are used instead, truncated
    after the k^-8 .. k^-9 terms (error < 1e-12 relative at k = 20)."""
    small = k < _K_ASYM
    ks = np.where(small, k, 1.0)
    r = 1.0 / np.where(small, _K_ASYM, k)
    r2 = r * r
    f0 = np.where(small, np.log(ks) - special.psi(ks),
                  0.5 * r + r2 * (1 / 12 + r2 * (-1 / 120 + r2 * (1 / 252 - r2 / 240))))
    f1 = np.where(small, 1.0 / ks - special.zeta(2.0, ks),    # trigamma = zeta(2, k)
                  -(0.5 * r2 + r2 * r * (1 / 6 + r2 * (-1 / 30 + r2 * (1 / 42 - r2 / 30)))))
    g = np.where(small, ks * np.log(ks) - special.gammaln(ks) - ks,
                 0.5 * np.log(1.0 / r) - _HALF_LN_2PI
                 - r * (1 / 12 + r2 * (-1 / 360 + r2 * (1 / 1260 - r2 / 1680))))
    return f0, f1, g


def _shape_terms_scalar(k: float) -> Tuple[float, float, float]:
    """Scalar twin of _shape_terms."""
    if k < _K_ASYM:
        return (math.log(k) - float(special.psi(k)), 1.0 / k - float(special.zeta(2.0, k)),
                k * math.log(k) - math.lgamma(k) - k)
    r = 1.0 / k
    r2 = r * r
    return (0.5 * r + r2 * (1 / 12 + r2 * (-1 / 120 + r2 * (1 / 252 - r2 / 240))),
            -(0.5 * r2 + r2 * r * (1 / 6 + r2 * (-1 / 30 + r2 * (1 / 42 - r2 / 30)))),
            0.5 * math.log(k) - _HALF_LN_2PI
            - r * (1 / 12 + r2 * (-1 / 360 + r2 * (1 / 1260 - r2 / 1680))))


def _kappa_lr(s: np.ndarray, n: int) -> Tuple[np.ndarray, np.ndarray]:
    """Vectorised (kappa_hat, LR) from the sufficient statistic s (see
    gamma_renewal_lrt). Shared by the MC generator and the exact table, and
    step-for-step equal to the runtime scalar path, so all use one LR(s) map."""
    s = np.maximum(np.asarray(s, dtype=np.float64), 0.0)
    capped = s <= _S_AT_KAPPA_MAX
    sv = np.where(capped, 1.0, s)                  # placeholder keeps the init finite
    k = (3.0 - sv + np.sqrt((sv - 3.0) ** 2 + 24.0 * sv)) / (12.0 * sv)   # Minka
    active = ~capped & np.isfinite(sv)
    for _ in range(_NEWTON_STEPS):
        if not active.any():
            break
        f0, f1, _ = _shape_terms(k)
        dk = np.where(active, -(f0 - sv) / f1, 0.0)
        k_new = k + dk
        k = np.where(k_new > 0.0, k_new, 0.5 * k)  # f is convex: never needed from Minka
        active &= np.abs(dk) >= _NEWTON_TOL
    k = np.where(capped, KAPPA_MAX, np.minimum(k, KAPPA_MAX))
    # 2 [l(k) - l(1)] / n with l(k)/n = k ln k - lnG(k) - k - k s - mean(ln x)
    g = _shape_terms(k)[2]
    lr = 2.0 * n * (g - k * s + 1.0 + s)
    lr = np.where(k > 1.0, np.maximum(lr, 0.0), 0.0)
    return k, lr


def _kappa_lr_scalar(s: float, n: int) -> Tuple[float, float]:
    """Scalar twin of _kappa_lr (same steps in plain floats: ~4x less numpy
    call overhead on the per-pair hot path; equal to ~1e-13, tested)."""
    s = max(s, 0.0)
    if s <= _S_AT_KAPPA_MAX:
        k = KAPPA_MAX
    else:
        k = (3.0 - s + math.sqrt((s - 3.0) ** 2 + 24.0 * s)) / (12.0 * s)
        for _ in range(_NEWTON_STEPS):
            f0, f1, _ = _shape_terms_scalar(k)
            dk = -(f0 - s) / f1
            k = k + dk if k + dk > 0.0 else 0.5 * k
            if abs(dk) < _NEWTON_TOL:
                break
        k = min(k, KAPPA_MAX)
    if not k > 1.0:
        return k, 0.0
    lr = 2.0 * n * (_shape_terms_scalar(k)[2] - k * s + 1.0 + s)
    return k, max(lr, 0.0)


# s at which the MLE reaches KAPPA_MAX (ln k - digamma(k) = s); below it the
# shape is capped, so LR(s) stays continuous and monotone in s.
_S_AT_KAPPA_MAX = _shape_terms_scalar(KAPPA_MAX)[0]


def gamma_renewal_lrt(intervals: Sequence[float]) -> Tuple[float, float]:
    """(kappa_hat, LR) of the Gamma-shape renewal test against Exp (kappa = 1).

    x = clip(intervals, MIN_INTERVAL_S), n = len(x), s = ln(mean x) - mean(ln x) >= 0.
    Minka init: kappa = (3 - s + sqrt((s - 3)^2 + 24 s)) / (12 s), then Newton on
        f(k) = ln k - digamma(k) - s,  f'(k) = 1/k - trigamma(k)
    for up to 4 steps (|dk| < 1e-8 stops). Profile log-likelihood with
    theta = mean/kappa:
        l(k) = n [k ln k - gammaln(k) - k ln(mean) + (k - 1) mean(ln x) - k]
    LR = 2 [l(kappa_hat) - l(1)] if kappa_hat > 1 else 0 (one-sided).
    kappa_hat is capped at KAPPA_MAX = 1e6 (LR is then the profile at the
    cap, which keeps LR(s) monotone): s ~ 0 (all equal) -> (1e6, ~14 n).
    NaN / inf intervals are dropped first and n counts the finite ones (pass
    that n to beacon_null_p). n < 3 -> (NaN, NaN). O(n).
    """
    x = np.asarray(intervals, dtype=np.float64).ravel()
    x = x[np.isfinite(x)]
    n = x.size
    if n < 3:
        return math.nan, math.nan
    x = np.maximum(x, MIN_INTERVAL_S)
    s = float(_log_ratio_stat(x))
    if s != s:
        return math.nan, math.nan
    return _kappa_lr_scalar(s, n)


def beacon_null_p(lr: float, n: int) -> float:
    """Upper-tail p of LR under the Poisson null from BEACON_NULL_LR.

    Row: largest tabulated n' <= n (conservative; n < 8 -> NaN; n > 256 ->
    row 256); n counts intervals (events - 1). Interpolate log10 p linearly
    in LR between tabulated quantiles (log p is convex in LR, so the chords
    err conservative, <= 0.025 decades), with the anchor (LR = 0, p = 1)
    below the first one (conservative: the true p just above 0 is
    P(LR > 0) ~ 0.53-0.66). LR <= 0 -> 1.0, NaN -> NaN.
    Beyond the last tabulated quantile LR_last, extrapolate log-linearly with
    the exact asymptotic slope of the row (in log space, floored at 1e-300):
        p = p_last * exp(-(n' - 1) / (2 n') * (LR - LR_last)).
    Why: as s -> 0, P0(s <= s0) ~ s0^((n-1)/2) (the simplex volume) while
    LR ~ -n ln s, so ln p ~ -(n-1)/(2n) LR; ln p is convex in LR, so its slope
    beyond the table lies between the last chord and that asymptote and the
    line is an upper bound. FIX: the stub's chi2_1 shape (slope -1/2 - 1/(2 LR))
    decays faster and was anti-conservative there (0.9 decades at n = 8,
    LR_last + 30; measured against the exact inversion).
    O(log len(N) + log len(LOG10P)).
    """
    try:
        lr = float(lr)
        n = float(n)
    except (TypeError, ValueError):
        return math.nan
    if lr != lr or n != n or n < BEACON_NULL_N[0]:
        return math.nan
    if lr <= 0.0:
        return 1.0
    row = bisect_right(BEACON_NULL_N, n) - 1
    xs, ys = _NULL_KNOTS[row]
    if lr <= xs[-1]:
        j = bisect_left(xs, lr)                    # xs[j-1] < lr <= xs[j], j >= 1
        x0, x1, y0, y1 = xs[j - 1], xs[j], ys[j - 1], ys[j]
        y = y1 if x1 <= x0 else y0 + (y1 - y0) * (lr - x0) / (x1 - x0)
        return 10.0 ** y
    n_row = BEACON_NULL_N[row]
    log_p = ys[-1] * _LN10 - (n_row - 1) / (2.0 * n_row) * (lr - xs[-1])
    return max(P_FLOOR, math.exp(log_p))


def _mc_null_lr(n: int, n_sims: int, rng: np.random.Generator) -> np.ndarray:
    """n_sims null LRs from i.i.d. Exp(1) intervals (the LR is scale-free),
    in blocks of ~1M variates to bound memory."""
    out = np.empty(int(n_sims), dtype=np.float64)
    step = max(1, (1 << 20) // n)
    for a in range(0, out.size, step):
        b = min(out.size, a + step)
        x = rng.standard_exponential((b - a, n))
        out[a:b] = _kappa_lr(_log_ratio_stat(x), n)[1]
    return out


def build_beacon_null_table(n_grid: Sequence[int] = BEACON_NULL_N,
                            log10p: Sequence[float] = BEACON_NULL_LOG10P,
                            n_sims: int = 100_000, seed: int = 20260927) -> np.ndarray:
    """Monte-Carlo estimate of BEACON_NULL_LR (offline, not called at runtime):
    simulate n_sims x n Exp(1) intervals per n, compute the gamma_renewal_lrt
    LR, and take the (1 - 10**log10p) empirical quantiles. Deterministic given
    seed (row n uses default_rng([seed, n]), so rows do not depend on the
    rest of the grid). Columns with fewer than 10 expected exceedances
    (n_sims * p < 10) cannot be resolved by simulation and are NaN.

    The shipped constants come from the exact null (_exact_null_lr_table);
    this estimator is their independent check (scripts/gen_beacon_null.py).
    """
    probs = 10.0 ** np.asarray(log10p, dtype=np.float64)
    table = np.full((len(n_grid), probs.size), np.nan)
    ok = probs * n_sims >= _MC_MIN_TAIL
    for i, n in enumerate(n_grid):
        n = int(n)
        rng = np.random.default_rng([int(seed), n])
        lr = _mc_null_lr(n, int(n_sims), rng)
        if ok.any():
            table[i, ok] = np.quantile(lr, 1.0 - probs[ok])
    return table


# ---- exact null of T = n s under i.i.d. Exp intervals (offline) -------------
def _null_cgf(u, n: int):
    """K(u) = ln E[exp(u T)] = -n u ln n + lnG(n) + n lnG(1 - u) - lnG(n (1 - u)),
    Re u < 1 (complex u allowed)."""
    return (-n * math.log(n)) * u + math.lgamma(n) + n * special.loggamma(1.0 - u) \
        - special.loggamma(n * (1.0 - u))


def _null_cgf_d1(c: float, n: int) -> float:
    return float(-n * math.log(n) - n * special.psi(1.0 - c) + n * special.psi(n * (1.0 - c)))


def _null_cgf_d2(c: float, n: int) -> float:
    return float(n * special.zeta(2.0, 1.0 - c) - n * n * special.zeta(2.0, n * (1.0 - c)))


def _null_log_cdf_T(t: float, n: int) -> float:
    """ln P0(T <= t), T = n (ln mean x - mean ln x), x_i i.i.d. Exp.

    Bromwich inversion on the line Re u = c through the saddlepoint K'(c) = t:
        c < 0:      P(T <= t) = (1/pi) int_0^inf Re[e^(K(u) - u t) / -u] dy
        0 < c < 1:  P(T >  t) = (1/pi) int_0^inf Re[e^(K(u) - u t) /  u] dy
    (u = c + iy; the lower form below the mean, the upper one above it, so
    neither is a small difference of O(1) numbers; c is kept >= 1/sd(T) away
    from the pole at 0). The trapezoid step is 1/6 of the distance to the
    nearest singularity or the saddle width, so the discretisation error is
    ~exp(-2 pi 6) relative; the |y|^(-(n+1)/2) tail is cut at 80 (1 + |c| + width).
    """
    from scipy import optimize

    if not t > 0.0:
        return -math.inf
    mu = _null_cgf_d1(0.0, n)
    w0 = 1.0 / math.sqrt(_null_cgf_d2(0.0, n))
    lower = t < mu
    if lower:
        lo = 1.0 - (n - 1) / t - 10.0            # K'(c) ~ (n-1) / (2 (1 - c)) < t there
        c_hat = optimize.brentq(lambda c: _null_cgf_d1(c, n) - t, lo, 0.0, xtol=1e-13, rtol=1e-15)
        c = min(c_hat, -w0)
        gap = -c
    else:
        hi = 1.0 - 1e-12                         # K'(c) -> +inf as c -> 1
        c_hat = optimize.brentq(lambda c: _null_cgf_d1(c, n) - t, 0.0, hi, xtol=1e-15, rtol=1e-15)
        c = max(c_hat, min(w0, 0.5))
        gap = min(c, 1.0 - c)                    # poles at 0 and (Gamma(1 - u)) at 1
    w = 1.0 / math.sqrt(_null_cgf_d2(c, n))
    h = min(w, gap) / 6.0
    y = np.arange(0.0, 80.0 * (1.0 + abs(c) + w), h)
    uu = c + 1j * y
    base = float(np.real(_null_cgf(c, n))) - c * t
    g = np.real(np.exp(_null_cgf(uu, n) - uu * t - base) / (-uu if lower else uu))
    val = h * (g.sum() - 0.5 * g[0]) / math.pi
    if not val > 0.0:
        raise FloatingPointError(f"null cdf inversion failed (n={n}, t={t})")
    if lower:
        return base + math.log(val)
    return math.log1p(-min(1.0, math.exp(base) * val))


def _exact_null_lr_quantiles(n: int, log10p: Sequence[float]) -> np.ndarray:
    """LR quantiles with P0(LR >= q) = 10**log10p for n intervals (exact)."""
    from scipy import optimize

    n = int(n)
    mu = _null_cgf_d1(0.0, n)
    sd = math.sqrt(_null_cgf_d2(0.0, n))
    t_hi = mu + 8.0 * sd                          # P0(T <= t_hi) ~ 1 for every column
    out = []
    for lp in log10p:
        target = float(lp) * _LN10
        t_lo = mu * 1e-3
        while _null_log_cdf_T(t_lo, n) > target:
            t_lo *= 1e-2
        t = optimize.brentq(lambda tt: _null_log_cdf_T(tt, n) - target, t_lo, t_hi,
                            xtol=1e-14 * mu, rtol=1e-14, maxiter=200)
        out.append(float(_kappa_lr(np.array([t / n]), n)[1][0]))
    return np.array(out)


def _exact_null_lr_table(n_grid: Sequence[int] = BEACON_NULL_N,
                         log10p: Sequence[float] = BEACON_NULL_LOG10P) -> np.ndarray:
    """The exact BEACON_NULL_LR (what scripts/gen_beacon_null.py pastes)."""
    return np.vstack([_exact_null_lr_quantiles(n, log10p) for n in n_grid])


# ============================================================ periodicity
def z2_trial_periods(span_s: float, p_min_s: float = 10.0, p_max_s: Optional[float] = None,
                     oversample: int = 5) -> Tuple[np.ndarray, float]:
    """(trial_periods, n_eff_trials) for the Z^2 scan.

    Frequencies from 1/p_max (default span/4) to 1/p_min in steps of
    1/(oversample * span) (periods returned descending); n_eff = (f_max -
    f_min) * span over the frequencies actually scanned (independent Fourier
    frequencies; z2_p turns it into the effective-trials correction).
    Capped at 512 trials: when the band needs more, the step first coarsens
    to cover it, down to an oversampling of Z2_MIN_OVERSAMPLE = 2 (a strict
    train then keeps >= 40% of its Z^2 at the worst offset; an unscanned
    frequency keeps 0%). If that is still not enough the grid stops after
    512 trials, i.e. it covers the long-period end: ~255 Fourier
    frequencies above 1/p_max, where a beacon of up to ~250 beats over the
    span sits. Callers after short periods over a long span narrow the band
    (e.g. p_max_s ~ 3x the median interval). span <= 0, non-finite inputs or
    p_min > p_max -> (empty, 0.0).
    """
    empty = np.empty(0, dtype=np.float64)
    span = float(span_s)
    if not (math.isfinite(span) and span > 0.0):
        return empty, 0.0
    p_max = span / 4.0 if p_max_s is None else float(p_max_s)
    p_min = float(p_min_s)
    if not (p_min > 0.0 and p_max > 0.0 and math.isfinite(p_min) and math.isfinite(p_max)):
        return empty, 0.0
    f_lo, f_hi = 1.0 / p_max, 1.0 / p_min
    if not f_hi >= f_lo:
        return empty, 0.0
    width = (f_hi - f_lo) * span                   # band in Fourier frequencies
    over = max(1.0, float(oversample))
    if width * over >= Z2_MAX_TRIALS:
        over = max(min(over, Z2_MIN_OVERSAMPLE), (Z2_MAX_TRIALS - 1) / width)
    df = 1.0 / (over * span)
    count = int(math.floor((f_hi - f_lo) / df * (1.0 + 1e-12))) + 1
    f = f_lo + df * np.arange(min(count, Z2_MAX_TRIALS))
    return 1.0 / f, float((f[-1] - f[0]) * span)


def _z2_sums_uniform(t: np.ndarray, f0: float, df: float, count: int, m: int) -> List[np.ndarray]:
    """Phasor sums S_k(f_j) = sum_i exp(2 pi i k f_j t_i), f_j = f0 + j df.

    With j = b R + r the phasor factorises, exp(i w (f0 + b R df) t) *
    exp(i w r df t), so S_k is a (B x n) @ (n x R) complex matmul of k-th
    powers. Both factors are geometric in their row index, so they are
    running products of 3 rows of exponentials (complex exp costs ~35 ns
    each, a multiply ~1 ns): 3 n exponentials instead of count * n, equal to
    the direct sum to ~1e-12 (the products drift by ~sqrt(count) ulp)."""
    r_blk = int(math.ceil(math.sqrt(count)))
    b_blk = -(-count // r_blk)
    tw = (2j * math.pi) * t
    inner = np.empty((r_blk, t.size), dtype=np.complex128)          # R x n
    inner[0] = 1.0
    if r_blk > 1:
        inner[1:] = np.exp(df * tw)
        np.cumprod(inner, axis=0, out=inner)                       # row r: e^(i w r df t)
    outer = np.empty((b_blk, t.size), dtype=np.complex128)          # B x n
    outer[0] = np.exp(f0 * tw)
    if b_blk > 1:
        outer[1:] = np.exp((r_blk * df) * tw)
        np.cumprod(outer, axis=0, out=outer)                       # row b: e^(i w (f0 + b R df) t)
    sums = []
    a, b = outer, inner
    for k in range(1, m + 1):
        if k > 1:
            a = a * outer
            b = b * inner
        sums.append((a @ b.T).ravel()[:count])
    return sums


def _z2_sums_direct(t: np.ndarray, f: np.ndarray, m: int) -> List[np.ndarray]:
    """Same sums for an arbitrary frequency list, in blocks of <= 64k phasors."""
    sums = [np.empty(f.size, dtype=np.complex128) for _ in range(m)]
    step = max(1, _Z2_CHUNK // max(1, t.size))
    for a in range(0, f.size, step):
        z = np.exp((2j * math.pi) * np.outer(f[a:a + step], t))
        zk = z
        for k in range(m):
            if k:
                zk = zk * z
            sums[k][a:a + step] = zk.sum(axis=1)
    return sums


def z2_periodogram(times: Sequence[float], trial_periods: Sequence[float], m: int = 2) -> np.ndarray:
    """Window-corrected Buccheri Z^2_m statistic for each trial period P:

        phi_i = 2 pi (t_i - t_min) / P,   T = t_max - t_min,  theta_k = 2 pi k T / P
        w_k   = E[exp(i k phi)] for t uniform on [t_min, t_max]
              = (exp(i theta_k) - 1) / (i theta_k)
        mu_k  = 1 + exp(i theta_k) + (n - 2) w_k
        Z^2_m = (2/(n - 2)) sum_{k=1..m} |sum_i exp(i k phi_i) - mu_k|^2
    mu_k is the mean given the two endpoint events, which define the window
    (FIX: n w_k ignored them; see the module docstring). A strict train over
    whole cycles gives Z^2_m = 2 m (n - 2); n = 2 gives 0.
    DEVIATION: the stub had no w_k term. w_k ~ P / (2 pi k T) only matters at
    the few lowest frequencies, where a non-integer number of cycles over
    the window makes Poisson phases non-uniform (Z^2 biased by ~2 n w^2,
    12x anti-conservative at n = 256); for a real period (integer cycles)
    it is ~0. Under the Poisson null the interior phases are uniform and
    Z^2_m ~ chi2_{2m} (slightly below it at small n). Time shifts do not
    change it. NaN times are dropped; n < 2 -> all NaN; invalid periods
    (<= 0, NaN) -> NaN there. A uniform frequency grid (z2_trial_periods)
    takes a factorised path costing 3 n exponentials, O(n L) multiplies and
    a small matmul (~0.3 ms at 256 x 512, m = 2); any other grid is the plain
    outer product O(n L m).
    """
    m = int(m)
    if m < 1:
        raise ValueError(f"z2_periodogram: m={m} must be >= 1")
    per = np.asarray(trial_periods, dtype=np.float64).ravel()
    t = np.asarray(times, dtype=np.float64).ravel()
    t = t[np.isfinite(t)]
    out = np.full(per.size, np.nan)
    n = t.size
    if n < 2 or per.size == 0:
        return out
    t = t - t.min()
    span = float(t.max())
    ok = np.isfinite(per) & (per > 0.0)
    if not ok.any():
        return out
    f = 1.0 / per[ok]
    count = f.size
    uniform = False
    if count >= 3:
        df = (f[-1] - f[0]) / (count - 1)
        uniform = bool(np.max(np.abs(np.diff(f) - df)) <= _Z2_UNIFORM_RTOL * np.max(np.abs(f)))
    if uniform:
        sums = _z2_sums_uniform(t, float(f[0]), float(df), count, m)
    else:
        sums = _z2_sums_direct(t, f, m)
    z2 = np.zeros(count)
    n_in = max(n - 2, 1)                           # n = 2: r == 0 exactly, Z^2 = 0
    for k, s in enumerate(sums, start=1):
        theta = (2.0 * math.pi * k * span) * f
        with np.errstate(invalid="ignore", divide="ignore"):
            w = np.where(np.abs(theta) > 1e-12, np.expm1(1j * theta) / (1j * theta), 1.0)
        # the endpoints sit at phases 0 and theta by construction; only the
        # n - 2 interior times are i.i.d. uniform on the window
        r = s - (1.0 + np.exp(1j * theta)) - (n - 2) * w
        z2 += r.real ** 2 + r.imag ** 2
    out[ok] = (2.0 / n_in) * z2
    return out


def z2_p(z2_max: float, m: int, n_eff_trials: float, n_trials: Optional[int] = None) -> float:
    """Trials-corrected p of the best Z^2 over a scanned band (Davies bound):

        p = min(1, chi2.sf(z, 2m) + n_eff c_m (z/2)^(m - 1/2) e^(-z/2) / Gamma(m))
        c_m = sqrt(pi (m + 1)(2m + 1) / 18)
    i.e. P(Z^2 at the band edge > z) + E[upcrossings of z inside the band]
    (Rice/Davies 1987 for a chi2_{2m} process: harmonic k's phasor has
    second spectral moment (2 pi k)^2 T^2/12 for events spread over T, and
    n_eff = band x T from z2_trial_periods). It bounds the continuous-band
    maximum, hence any grid. With n_trials = len(trial_periods) the union
    bound n_trials * chi2.sf(z, 2m) over the actual grid is also valid and
    the smaller is used: it wins on the 2x-oversampled grids of long spans
    (Davies is ~3x conservative there at alarm levels) and loses on 5x ones.
    DEVIATION: the stub used n_eff * chi2.sf(z, 2m), measured 2-5x
    anti-conservative on a 5x-oversampled scan (the effective number of
    trials grows ~ sqrt(z/2)). Log space, floored at 1e-300. NaN -> NaN;
    z <= 0 -> 1. n_trials (optional, backward compatible) <= 0 is ignored.
    """
    z = float(z2_max)
    m = int(m)
    w = float(n_eff_trials)
    if z != z or w != w or m < 1:
        return math.nan
    if z <= 0.0:
        return 1.0
    h = 0.5 * z
    log_h = math.log(h)
    # chi2_{2m} sf = e^-h sum_{j<m} h^j / j!
    log_terms = [j * log_h - math.lgamma(j + 1.0) for j in range(m)]
    lmax = max(log_terms)
    sf = math.exp(-h + lmax + math.log(sum(math.exp(v - lmax) for v in log_terms)))
    p = sf
    if w > 0.0:
        c_m = math.sqrt(math.pi * (m + 1) * (2 * m + 1) / 18.0)
        p += math.exp(math.log(w * c_m) + (m - 0.5) * log_h - h - math.lgamma(m))
    if n_trials is not None and n_trials > 0:
        p = min(p, n_trials * sf)
    return min(1.0, max(P_FLOOR, p))


def rayleigh_p(times: Sequence[float], period: float) -> float:
    """Rayleigh test p at one period (B11 strict periodicity, descriptor for B12).

    phi_i = 2 pi t_i / period, Rn = |sum exp(i phi_i)| (resultant length),
    p = exp(sqrt(1 + 4n + 4(n^2 - Rn^2)) - (1 + 2n))  (Zar 1999), clipped to [0, 1].
    Times are shifted by t_min first (Rn is shift-invariant; this keeps the
    phases small and exact). NaN times are dropped; n < 2 or an invalid
    period -> NaN.
    """
    t = np.asarray(times, dtype=np.float64).ravel()
    t = t[np.isfinite(t)]
    n = t.size
    period = float(period)
    if n < 2 or not (period > 0.0 and math.isfinite(period)):
        return math.nan
    ph = (2.0 * math.pi / period) * (t - t.min())
    rn2 = float(np.cos(ph).sum()) ** 2 + float(np.sin(ph).sum()) ** 2
    p = math.exp(math.sqrt(1.0 + 4.0 * n + 4.0 * max(0.0, n * n - rn2)) - (1.0 + 2.0 * n))
    return min(1.0, max(0.0, p))


# ---- beacon null interpolation knots (built once at import) -----------------
def _build_knots(table: Optional[np.ndarray]) -> List[Tuple[Tuple[float, ...], Tuple[float, ...]]]:
    if table is None:
        return []
    knots = []
    for row in np.asarray(table, dtype=np.float64):
        xs, ys = [0.0], [0.0]                      # anchor: LR = 0 -> p = 1
        for x, y in zip(row.tolist(), BEACON_NULL_LOG10P):
            if x > xs[-1] or (x == xs[-1] and len(xs) > 1):
                xs.append(x)
                ys.append(y)
        knots.append((tuple(xs), tuple(ys)))
    return knots


_NULL_KNOTS = _build_knots(BEACON_NULL_LR)
